spring:
  web:
#    resources:
#      static-locations: classpath:/static/,file:${file.upload.dir}
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入

  datasource:

    url: jdbc:mysql://localhost:3306/DB?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:resources/mybatis/mapper/*.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
file:
  upload:
    #dir: /home
    dir: C:\a
#  可以不写全局；配置文件，所有全局配置文件的配置都放在configuration配置项中即可
